# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2b134597f01de50161eddc25910b9181ad12732ec54f565b40e7dac9792db63026261d5050d9b8a37c4d29bfc78a113bae5ee6372259775973967e8e1712352

test:
  secret_key_base: afb2334f2e844197e7233ed306e0c1f5709b66248a16223e1392bedba83aa1b5fd993ab4e88933d18ca32f65f96bb2a3a9079f1f3b096e9843e2e97a8220b233

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
